ansible:
  playbooks_dir: examples/playbooks
  inventory_path: examples/inventory.txt

workers: 5

routing_keys:
    - org.fedoraproject.dev.logger.hello_world

plugins:
  looper:
    name: redis
    host: 127.0.0.1
    port: 6379
    db: 0
  translator:
    name: rkdirectory
